---
- name: Setup SSH Key Authentication for Remote Server
  hosts: incus_server
  become: yes
  vars:
    ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/incus_server_key.pub"
    
  pre_tasks:
    - name: Check if local SSH key exists
      ansible.builtin.stat:
        path: "{{ ssh_key_path }}"
      delegate_to: localhost
      register: ssh_key_stat
      become: no

    - name: Fail if SSH key doesn't exist
      ansible.builtin.fail:
        msg: |
          SSH public key not found at {{ ssh_key_path }}
          Please run 'just generate-ssh-key' first to create the SSH key pair
      when: not ssh_key_stat.stat.exists

    - name: Display setup information
      ansible.builtin.debug:
        msg:
          - "Setting up SSH key authentication for server: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "SSH key: {{ ssh_key_path }}"

  tasks:
    - name: Ensure .ssh directory exists for user
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'
      become_user: "{{ ansible_user }}"

    - name: Read local SSH public key
      ansible.builtin.slurp:
        src: "{{ ssh_key_path }}"
      delegate_to: localhost
      register: ssh_public_key
      become: no

    - name: Deploy SSH public key to authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_public_key.content | b64decode | trim }}"
        comment: "incus-server-key-{{ ansible_date_time.date }}"
        exclusive: no

    - name: Test SSH key authentication
      ansible.builtin.command: whoami
      register: whoami_result
      become: no

    - name: Display success message
      ansible.builtin.debug:
        msg:
          - "✅ SSH public key deployed successfully!"
          - "Server: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "Test result: Connected as {{ whoami_result.stdout }}"
          - ""
          - "⚠️  IMPORTANT: Test the SSH key connection before disabling password auth!"
          - "Run: just test-ssh-key-connection"